/**
 * The negative set: pages that must NOT show Discussions, per the product
 * owner's objection — organisation homepages and generic "everlasting" pages
 * that nonetheless carry Hacker News submissions.
 *
 * Plus a comparison POSITIVE set, deliberately weighted toward the hard cases
 * (essays resubmitted over years), so overlap can be measured rather than
 * assumed away.
 */

/** @type {Array<[string, string]>} url, category */
export const NEGATIVE = [
  // --- A. Big-tech / platform homepages ---
  ["https://www.facebook.com/", "org-homepage"],
  ["https://github.com/", "org-homepage"],
  ["https://www.google.com/", "org-homepage"],
  ["https://x.com/", "org-homepage"],
  ["https://twitter.com/", "org-homepage"],
  ["https://www.apple.com/", "org-homepage"],
  ["https://openai.com/", "org-homepage"],
  ["https://stripe.com/", "org-homepage"],
  ["https://www.cloudflare.com/", "org-homepage"],
  ["https://www.wikipedia.org/", "org-homepage"],
  ["https://www.reddit.com/", "org-homepage"],
  ["https://www.amazon.com/", "org-homepage"],
  ["https://www.microsoft.com/", "org-homepage"],
  ["https://www.netflix.com/", "org-homepage"],
  ["https://www.nvidia.com/", "org-homepage"],
  ["https://www.tesla.com/", "org-homepage"],
  ["https://www.spotify.com/", "org-homepage"],
  ["https://www.airbnb.com/", "org-homepage"],
  ["https://www.uber.com/", "org-homepage"],
  ["https://www.linkedin.com/", "org-homepage"],
  ["https://www.dropbox.com/", "org-homepage"],
  ["https://slack.com/", "org-homepage"],
  ["https://www.notion.so/", "org-homepage"],
  ["https://www.figma.com/", "org-homepage"],
  ["https://vercel.com/", "org-homepage"],
  ["https://www.netlify.com/", "org-homepage"],
  ["https://www.digitalocean.com/", "org-homepage"],
  ["https://www.heroku.com/", "org-homepage"],
  ["https://www.mozilla.org/", "org-homepage"],
  ["https://www.anthropic.com/", "org-homepage"],
  ["https://huggingface.co/", "org-homepage"],
  ["https://about.gitlab.com/", "org-homepage"],
  ["https://www.docker.com/", "org-homepage"],
  ["https://www.npmjs.com/", "org-homepage"],
  ["https://www.atlassian.com/", "org-homepage"],
  ["https://www.oracle.com/", "org-homepage"],
  ["https://www.ibm.com/", "org-homepage"],
  ["https://www.intel.com/", "org-homepage"],
  ["https://www.adobe.com/", "org-homepage"],
  ["https://www.salesforce.com/", "org-homepage"],

  // --- B. Banks / finance (the product owner's own example) ---
  ["https://www.bankofamerica.com/", "finance-homepage"],
  ["https://www.chase.com/", "finance-homepage"],
  ["https://www.wellsfargo.com/", "finance-homepage"],
  ["https://www.citibank.com/", "finance-homepage"],
  ["https://www.goldmansachs.com/", "finance-homepage"],
  ["https://www.jpmorgan.com/", "finance-homepage"],
  ["https://www.paypal.com/", "finance-homepage"],
  ["https://www.coinbase.com/", "finance-homepage"],
  ["https://robinhood.com/", "finance-homepage"],
  ["https://www.revolut.com/", "finance-homepage"],
  ["https://wise.com/", "finance-homepage"],
  ["https://squareup.com/", "finance-homepage"],
  ["https://www.visa.com/", "finance-homepage"],
  ["https://www.klarna.com/", "finance-homepage"],

  // --- C. News homepages ---
  ["https://www.nytimes.com/", "news-homepage"],
  ["https://www.washingtonpost.com/", "news-homepage"],
  ["https://www.theguardian.com/", "news-homepage"],
  ["https://www.bbc.com/", "news-homepage"],
  ["https://www.wsj.com/", "news-homepage"],
  ["https://www.ft.com/", "news-homepage"],
  ["https://www.reuters.com/", "news-homepage"],
  ["https://www.bloomberg.com/", "news-homepage"],
  ["https://www.cnn.com/", "news-homepage"],
  ["https://techcrunch.com/", "news-homepage"],
  ["https://arstechnica.com/", "news-homepage"],
  ["https://www.theverge.com/", "news-homepage"],
  ["https://www.wired.com/", "news-homepage"],
  ["https://www.economist.com/", "news-homepage"],
  ["https://www.npr.org/", "news-homepage"],
  ["https://www.aljazeera.com/", "news-homepage"],
  ["https://apnews.com/", "news-homepage"],
  ["https://www.theatlantic.com/", "news-homepage"],
  ["https://www.newyorker.com/", "news-homepage"],
  ["https://www.vox.com/", "news-homepage"],
  ["https://www.politico.com/", "news-homepage"],
  ["https://www.engadget.com/", "news-homepage"],
  ["https://slashdot.org/", "news-homepage"],
  ["https://lwn.net/", "news-homepage"],

  // --- D. News section / index pages ---
  ["https://www.nytimes.com/section/technology", "news-section"],
  ["https://www.nytimes.com/section/business", "news-section"],
  ["https://www.theguardian.com/technology", "news-section"],
  ["https://www.theguardian.com/us-news", "news-section"],
  ["https://www.bbc.co.uk/news", "news-section"],
  ["https://www.reuters.com/technology/", "news-section"],
  ["https://www.bloomberg.com/technology", "news-section"],
  ["https://arstechnica.com/gadgets/", "news-section"],
  ["https://www.theverge.com/tech", "news-section"],
  ["https://www.wired.com/category/security/", "news-section"],
  ["https://www.washingtonpost.com/technology/", "news-section"],
  ["https://www.economist.com/science-and-technology", "news-section"],
  ["https://www.ft.com/technology", "news-section"],
  ["https://www.npr.org/sections/technology/", "news-section"],
  ["https://www.cnn.com/business/tech", "news-section"],

  // --- E. Docs roots ---
  ["https://developer.mozilla.org/", "docs-root"],
  ["https://docs.python.org/3/", "docs-root"],
  ["https://react.dev/", "docs-root"],
  ["https://nodejs.org/en", "docs-root"],
  ["https://www.rust-lang.org/", "docs-root"],
  ["https://doc.rust-lang.org/book/", "docs-root"],
  ["https://go.dev/", "docs-root"],
  ["https://kubernetes.io/", "docs-root"],
  ["https://docs.docker.com/", "docs-root"],
  ["https://www.postgresql.org/", "docs-root"],
  ["https://www.sqlite.org/", "docs-root"],
  ["https://www.typescriptlang.org/", "docs-root"],
  ["https://tailwindcss.com/", "docs-root"],
  ["https://vuejs.org/", "docs-root"],
  ["https://svelte.dev/", "docs-root"],
  ["https://docs.github.com/en", "docs-root"],
  ["https://docs.aws.amazon.com/", "docs-root"],
  ["https://www.gnu.org/software/emacs/", "docs-root"],
  ["https://man7.org/linux/man-pages/", "docs-root"],
  ["https://developer.apple.com/documentation/", "docs-root"],

  // --- F. Product landing pages ---
  ["https://linear.app/", "product-landing"],
  ["https://supabase.com/", "product-landing"],
  ["https://planetscale.com/", "product-landing"],
  ["https://railway.app/", "product-landing"],
  ["https://fly.io/", "product-landing"],
  ["https://render.com/", "product-landing"],
  ["https://www.cursor.com/", "product-landing"],
  ["https://obsidian.md/", "product-landing"],
  ["https://tailscale.com/", "product-landing"],
  ["https://www.raycast.com/", "product-landing"],
  ["https://zed.dev/", "product-landing"],
  ["https://bun.sh/", "product-landing"],
  ["https://deno.com/", "product-landing"],
  ["https://astro.build/", "product-landing"],
  ["https://duckdb.org/", "product-landing"],

  // --- G. Pricing pages ---
  ["https://stripe.com/pricing", "pricing"],
  ["https://vercel.com/pricing", "pricing"],
  ["https://openai.com/pricing", "pricing"],
  ["https://github.com/pricing", "pricing"],
  ["https://www.notion.so/pricing", "pricing"],
  ["https://slack.com/pricing", "pricing"],
  ["https://www.figma.com/pricing/", "pricing"],
  ["https://www.cloudflare.com/plans/", "pricing"],
  ["https://aws.amazon.com/pricing/", "pricing"],
  ["https://fly.io/docs/about/pricing/", "pricing"],
  ["https://supabase.com/pricing", "pricing"],
  ["https://www.anthropic.com/pricing", "pricing"],

  // --- H. Login / account pages ---
  ["https://accounts.google.com/", "login"],
  ["https://github.com/login", "login"],
  ["https://twitter.com/login", "login"],
  ["https://www.facebook.com/login", "login"],
  ["https://www.linkedin.com/login", "login"],
  ["https://www.reddit.com/login", "login"],
  ["https://www.netflix.com/login", "login"],
  ["https://id.atlassian.com/login", "login"],
  ["https://app.slack.com/", "login"],
  ["https://login.microsoftonline.com/", "login"],

  // --- I. Feeds / aggregators / search (self-referential destinations) ---
  ["https://news.ycombinator.com/", "feed-aggregator"],
  ["https://news.ycombinator.com/newest", "feed-aggregator"],
  ["https://www.reddit.com/r/programming/", "feed-aggregator"],
  ["https://www.reddit.com/r/technology/", "feed-aggregator"],
  ["https://medium.com/", "feed-aggregator"],
  ["https://substack.com/", "feed-aggregator"],
  ["https://www.youtube.com/", "feed-aggregator"],
  ["https://www.twitch.tv/", "feed-aggregator"],
  ["https://stackoverflow.com/", "feed-aggregator"],
  ["https://www.quora.com/", "feed-aggregator"],
  ["https://www.producthunt.com/", "feed-aggregator"],
  ["https://lobste.rs/", "feed-aggregator"],

  // --- J. Institutions / government / commerce ---
  ["https://www.mit.edu/", "institution"],
  ["https://www.stanford.edu/", "institution"],
  ["https://www.harvard.edu/", "institution"],
  ["https://www.nasa.gov/", "institution"],
  ["https://www.whitehouse.gov/", "institution"],
  ["https://www.irs.gov/", "institution"],
  ["https://www.un.org/", "institution"],
  ["https://www.who.int/", "institution"],
  ["https://www.worldbank.org/", "institution"],
  ["https://archive.org/", "institution"],
  ["https://www.craigslist.org/", "institution"],
  ["https://www.ebay.com/", "institution"],
  ["https://www.walmart.com/", "institution"],
  ["https://www.ycombinator.com/", "institution"],
  ["https://www.eff.org/", "institution"],
  ["https://www.consumerfinance.gov/", "institution"]
]

/**
 * Comparison positive set. NOT the authoritative positive set — that is another
 * agent's job. This exists only so the overlap between the two distributions
 * can be measured on data gathered under identical rules. Deliberately
 * weighted toward the counterexample class: classics resubmitted over years.
 */
export const POSITIVE = [
  // --- The counterexample class: essays resubmitted over years ---
  ["https://paulgraham.com/greatwork.html", "evergreen-essay"],
  ["https://paulgraham.com/genius.html", "evergreen-essay"],
  ["https://paulgraham.com/makersschedule.html", "evergreen-essay"],
  ["https://paulgraham.com/disagree.html", "evergreen-essay"],
  ["https://paulgraham.com/hp.html", "evergreen-essay"],
  ["https://paulgraham.com/love.html", "evergreen-essay"],
  ["https://www.cs.cmu.edu/~rdriley/487/papers/Thompson_1984_ReflectionsonTrustingTrust.pdf", "evergreen-essay"],
  ["https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/", "evergreen-essay"],
  ["https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/", "evergreen-essay"],
  ["https://danluu.com/everything-is-broken/", "evergreen-essay"],
  ["https://www.kalzumeus.com/2012/01/23/salary-negotiation/", "evergreen-essay"],
  ["https://norvig.com/21-days.html", "evergreen-essay"],
  ["https://www.gwern.net/Spaced-repetition", "evergreen-essay"],
  ["https://slatestarcodex.com/2014/07/30/meditations-on-moloch/", "evergreen-essay"],
  ["https://waitbutwhy.com/2015/01/artificial-intelligence-revolution-1.html", "evergreen-essay"],
  ["http://www.catb.org/~esr/faqs/smart-questions.html", "evergreen-essay"],
  ["https://grugbrain.dev/", "evergreen-essay"],
  ["https://ciechanow.ski/gears/", "evergreen-essay"],
  ["https://ciechanow.ski/gps/", "evergreen-essay"],
  ["https://jvns.ca/blog/2016/09/18/some-questions-about-networking/", "evergreen-essay"],

  // --- Dated news / blog items: the clean positive case ---
  ["https://openai.com/index/introducing-chatgpt-and-whisper-apis/", "dated-item"],
  ["https://blog.cloudflare.com/deep-dive-cloudflare-october-2023-outage/", "dated-item"],
  ["https://github.blog/2022-06-21-github-copilot-is-generally-available-to-all-developers/", "dated-item"],
  ["https://stripe.com/blog/negative-engineering", "dated-item"],
  ["https://blog.rust-lang.org/2021/11/01/cve-2021-42574.html", "dated-item"],
  ["https://www.anthropic.com/news/claude-3-family", "dated-item"],
  ["https://netflixtechblog.com/introducing-bpftop-a-tool-for-monitoring-ebpf-applications-431c8d1c8ffc", "dated-item"],
  ["https://blog.cloudflare.com/post-quantum-for-all/", "dated-item"],
  ["https://simonwillison.net/2023/Aug/3/weird-world-of-llms/", "dated-item"],
  ["https://www.nytimes.com/2023/03/29/technology/ai-artificial-intelligence-musk-risks.html", "dated-item"],
  ["https://arstechnica.com/security/2024/03/backdoor-found-in-widely-used-linux-utility-breaks-encrypted-ssh-connections/", "dated-item"],
  ["https://www.theverge.com/2023/11/17/23965982/openai-ceo-sam-altman-fired", "dated-item"],
  ["https://techcrunch.com/2023/03/10/svb-collapse/", "dated-item"],
  ["https://www.bbc.com/news/technology-68025677", "dated-item"],
  ["https://blog.mozilla.org/en/mozilla/firefox-quantum-developer-edition/", "dated-item"],
  ["https://engineering.fb.com/2021/10/04/networking-traffic/outage/", "dated-item"],
  ["https://about.gitlab.com/blog/2017/02/10/postmortem-of-database-outage-of-january-31/", "dated-item"],
  ["https://aws.amazon.com/message/41926/", "dated-item"],
  ["https://blog.pragmaticengineer.com/the-scoop-inside-the-longest-atlassian-outage/", "dated-item"],
  ["https://www.wired.com/story/the-untold-story-of-notpetya-the-most-devastating-cyberattack-in-history/", "dated-item"],

  // --- Deep pages that are documents but live on "generic" org domains ---
  ["https://github.blog/2023-11-08-universe-2023-copilot-transforms-github-into-the-ai-powered-developer-platform/", "dated-item"],
  ["https://research.google/blog/transformer-a-novel-neural-network-architecture-for-language-understanding/", "dated-item"],
  ["https://en.wikipedia.org/wiki/Byzantine_fault", "wiki-article"],
  ["https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect", "wiki-article"],
  ["https://en.wikipedia.org/wiki/Therac-25", "wiki-article"],
  ["https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API", "docs-page"],
  ["https://docs.python.org/3/library/asyncio.html", "docs-page"],
  ["https://go.dev/blog/generics-proposal", "dated-item"],
  ["https://sqlite.org/whybytecode.html", "docs-page"],
  ["https://www.sqlite.org/lang_with.html", "docs-page"]
]
